method: random  # You can use "grid", "random", or "bayes"
metric:
  name: val_accuracy
  goal: maximize
parameters:
  learning_rate:
    min: 0.0001
    max: 0.01
  dropout_rate:
    values: [0.3, 0.4, 0.5]
  filters:
    values: [[16, 32, 64], [20, 40, 80], [32, 64, 128], [64, 128, 256]]
  epochs:
    values: [50, 100, 125, 150, 200]
count: 50
